export const RAPPORT_OPTIONS = [
  { value: "", label: "Tous les rapports" },
  {
    value: "NOUVEAU PROSPECT",
    label: "Nouveau Prospect",
    color: "info" as const,
  },
  { value: "NRP", label: "NRP", color: "warning" as const },
  { value: "NRP 1", label: "NRP 1", color: "warning" as const },
  { value: "NRP 2", label: "NRP 2", color: "warning" as const },
  { value: "NRP 3", label: "NRP 3", color: "warning" as const },
  { value: "NRP 4", label: "NRP 4", color: "warning" as const },
  { value: "NRP 5", label: "NRP 5", color: "warning" as const },
  { value: "CLIENT", label: "Client", color: "success" as const },
  { value: "PERDU", label: "Perdu", color: "error" as const },
  { value: "RDV PRIS", label: "RDV Pris", color: "success" as const },
  { value: "A RAPPELER", label: "À Rappeler", color: "warning" as const },
  { value: "DEVIS ENVOYE", label: "Devis Envoyé", color: "info" as const },
  {
    value: "DEVIS ENVOYE NRP 1",
    label: "Devis Envoyé NRP 1",
    color: "warning" as const,
  },
  {
    value: "DEVIS ENVOYE NRP 2",
    label: "Devis Envoyé NRP 2",
    color: "warning" as const,
  },
  {
    value: "PROSPECT A RETRAITER",
    label: "Prospect à Retraiter",
    color: "warning" as const,
  },
  { value: "DOUBLON", label: "Doublon", color: "error" as const },
];

export const SOURCE_OPTIONS = [
  "2D CONSULTING",
  "BOX-TV",
  "CLOCHE",
  "CONTACT_AMBASSADEUR",
  "CONTROLE QUALITE",
  "DATA",
  "DATA LP",
  "ELITE",
  "ETUDE-THERMIQUE-GRATUITE-BOX",
  "ETUDE-THERMIQUE-GRATUITE-TNT",
  "FL",
  "FLEURON INDUSTRIES - CROSS COM",
  "FLEURON INDUSTRIES - PUB TV",
  "FORMULAIRE TERRAIN",
  "FORMULAIRE TERRAIN julien",
  "H LEADS",
  "IFLEURON",
  "INTERNE",
  "LEADS STEEVE",
  "LOGICALL",
  "LOGICALL PVWATT",
  "LOOPS",
  "Maison_Fleuron",
  "META",
  "NEL",
  "PARRAINAGE",
  "PV STEEVE",
  "RENEOV",
  "RETOUR MAILING",
  "RICHARD PARTNERS",
  "site-fleuronindustries",
  "STEVENS",
  "TIKTOK",
  "TIKTOK_BRUNO",
  "TIKTOK_JESSICA",
  "TIKTOK_JOSE",
  "TNT",
  "UNITEAD",
  "UNITEAD HD",
  "UNITEAD-CRG",
  "UNYX",
  "VOLTADS",
  "YITE",
  "YONI-HENRY",
];

export const TYPE_INSTALLATION_OPTIONS = [
  "ITE",
  "LED INTERIEUR",
  "POMPE A CHALEUR",
];

export const SMS_EMAIL_OPTIONS = [
  { value: "all", label: "Tous" },
  { value: "yes", label: "Envoyé" },
  { value: "no", label: "Non envoyé" },
];

export const TEMPLATE_VARIABLES = [
  { key: "nom", label: "Nom", example: "DUPONT" },
  { key: "prenom", label: "Prénom", example: "Jean" },
  { key: "ref", label: "Référence", example: "47750" },
  { key: "mobile", label: "Mobile", example: "06 12 34 56 78" },
  { key: "date", label: "Date", example: "26/01/2026" },
  { key: "source", label: "Source", example: "LOGICALL" },
  { key: "typeInstallation", label: "Type Installation", example: "ITE" },
];
